export const postData = [
  {
    handle: "@Professor Whiskerton",
    profilePic: "./images/professor.jpg",
    likes: 37,
    repost: 5,
    postText: "No food at 6:00 today. Taking note of this.",
    replies: [],
    isLiked: false,
    isReposted: false,
    uuid: "98sdf7s-d7fs-4f3d-93f3-87gdf6s5g4d6",
  },
  {
    handle: "@Luna Shadowpaws",
    profilePic: "./images/Luna.jpg",
    likes: 403,
    repost: 7,
    postText: "My human catched me some fish today! Such a good human.",
    replies: [],
    isLiked: false,
    isReposted: false,
    uuid: "8d7fsd9s-d7fs-4f3d-93f3-87gdf6s5g4d6",
  },
  {
    handle: "@Sir Meows-a-Lot",
    profilePic: "./images/meowalot.jpg",
    likes: 63,
    repost: 5,
    postText: "There was a red dot on the wall. I chased it for hours.",
    replies: [],
    isLiked: false,
    isReposted: false,
    uuid: "ff98d7s-d7fs-4f3d-93f3-87gdf6s5g4d6",
  },
];
